[package]
name = "node_mem_log"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }